services:
  db:
    image: postgres:15-alpine
    container_name: vendix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vendix_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - vendix_pgdata:/var/lib/postgresql/data
    networks:
      - vendix_net

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: vendix_backend
    restart: unless-stopped
    env_file:
      - ./apps/backend/.env
    environment:
      DATABASE_URL: postgres://username:password@db:5432/vendix_db?schema=public
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    networks:
      - vendix_net
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: vendix_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://api.vendix.com
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - vendix_net
    command: sh -c "npx ng serve --host 0.0.0.0 --poll 2000"

  nginx:
    image: nginx:alpine
    container_name: vendix_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./pages:/usr/share/nginx/html/pages
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - backend
      - frontend
    networks:
      - vendix_net

volumes:
  vendix_pgdata:

networks:
  vendix_net:
    driver: bridge
