services:
  db:
    image: postgres:15-alpine
    container_name: vendix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vendix_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - vendix_pgdata:/var/lib/postgresql/data
    networks:
      - vendix_net

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: vendix_backend
    restart: unless-stopped
    env_file:
      - ./apps/backend/.env
    environment:
      DATABASE_URL: postgres://username:password@db:5432/vendix_db?schema=public
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend/src:/app/src
      - ./apps/backend/prisma:/app/prisma
      - ./apps/backend/package.json:/app/package.json
      - ./apps/backend/package-lock.json:/app/package-lock.json
      - ./apps/backend/tsconfig.json:/app/tsconfig.json
      - ./apps/backend/tsconfig.*.json:/app/tsconfig.*.json
      - ./apps/backend/nest-cli.json:/app/nest-cli.json
      - ./apps/backend/.env:/app/.env
      - backend_node_modules:/app/node_modules
    networks:
      - vendix_net

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: vendix_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/package.json:/app/package.json
      - ./apps/frontend/package-lock.json:/app/package-lock.json
      - ./apps/frontend/angular.json:/app/angular.json
      - ./apps/frontend/tsconfig.json:/app/tsconfig.json
      - ./apps/frontend/tsconfig.*.json:/app/tsconfig.*.json
      - node_modules:/app/node_modules
    networks:
      - vendix_net

  nginx:
    image: nginx:alpine
    container_name: vendix_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./pages:/usr/share/nginx/html/pages
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - backend
      - frontend
    networks:
      - vendix_net

volumes:
  vendix_pgdata:
  node_modules:
  backend_node_modules:

networks:
  vendix_net:
    driver: bridge
